# Generated by Django 3.2.9 on 2023-02-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_label', models.CharField(default='button', max_length=30)),
                ('button_text', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
